Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,9 +34,9 @@ jobs:
       - name: Configure SSH Key
         run: |
           mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/heena.pem
-          chmod 600 ~/.ssh/heena.pem
-          ssh-keygen -y -f ~/.ssh/heena.pem > ~/.ssh/heena.pub || echo "Invalid key"
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/key.pem
+          chmod 600 ~/.ssh/key.pem
+          ssh-keygen -y -f ~/.ssh/key.pem > ~/.ssh/key.pub || echo "Invalid key"
 
       - name: Add SSH Host Key to Known Hosts
         run: |
